export const GETPRODUCTS_SUCCESS = 'GETPRODUCTS_SUCCESS';
export const GETPRODUCTS_FAILED = 'GETPRODUCTS_FAILED';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const SET_AUTH = 'SET_AUTH'; 
export const RESET_CART = 'RESET_CART';  
export const SET_CART = 'SET_CART';  
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const SEARCH_CART = 'SEARCH_CART';

export const ADDTO_SAVEFORLATER = 'ADDTO_SAVEFORLATER';
export const REMOVEFROM_SAVEFORLATER = 'REMOVEFROM_SAVEFORLATER';
export const REMOVEFROM_SAVEFORLATER_AND_ADDTOCART = 'REMOVEFROM_SAVEFORLATER_AND_ADDTOCART';

export const SET_ADDRESS_BOOK = 'SET_ADDRESS_BOOK';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const SELECT_ADDRESS = 'SELECT_ADDRESS';

export const PLACE_ORDER = 'PLACE_ORDER';
export const RESET_ORDER_ID = 'RESET_ORDER_ID';
export const GET_MY_ORDERS = 'GET_MY_ORDERS';
export const DELETE_ORDER = 'DELETE_ORDER';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const RESET_PRODUCT_ID = 'RESET_PRODUCT_ID';

export const SET_CATEGORY = 'SET_CATEGORY';

export const SET_SORT = 'SET_SORT';

export const UPDATE_USER = 'UPDATE_USER';